# Generated by Django 3.0.6 on 2021-01-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_as', '0002_komentarz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentarz',
            old_name='id_post',
            new_name='post',
        ),
    ]
