# Generated by Django 3.0.6 on 2021-01-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt_as', '0003_auto_20210111_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentarz',
            name='post',
        ),
    ]
